// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckPermissionParams creates a new CheckPermissionParams object
// with the default values initialized.
func NewCheckPermissionParams() *CheckPermissionParams {
	var ()
	return &CheckPermissionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckPermissionParamsWithTimeout creates a new CheckPermissionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckPermissionParamsWithTimeout(timeout time.Duration) *CheckPermissionParams {
	var ()
	return &CheckPermissionParams{

		timeout: timeout,
	}
}

// NewCheckPermissionParamsWithContext creates a new CheckPermissionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckPermissionParamsWithContext(ctx context.Context) *CheckPermissionParams {
	var ()
	return &CheckPermissionParams{

		Context: ctx,
	}
}

// NewCheckPermissionParamsWithHTTPClient creates a new CheckPermissionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckPermissionParamsWithHTTPClient(client *http.Client) *CheckPermissionParams {
	var ()
	return &CheckPermissionParams{
		HTTPClient: client,
	}
}

/*CheckPermissionParams contains all the parameters to send to the API endpoint
for the check permission operation typically these are written to a http.Request
*/
type CheckPermissionParams struct {

	/*Access*/
	Access CheckPermissionBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check permission params
func (o *CheckPermissionParams) WithTimeout(timeout time.Duration) *CheckPermissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check permission params
func (o *CheckPermissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check permission params
func (o *CheckPermissionParams) WithContext(ctx context.Context) *CheckPermissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check permission params
func (o *CheckPermissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check permission params
func (o *CheckPermissionParams) WithHTTPClient(client *http.Client) *CheckPermissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check permission params
func (o *CheckPermissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccess adds the access to the check permission params
func (o *CheckPermissionParams) WithAccess(access CheckPermissionBody) *CheckPermissionParams {
	o.SetAccess(access)
	return o
}

// SetAccess adds the access to the check permission params
func (o *CheckPermissionParams) SetAccess(access CheckPermissionBody) {
	o.Access = access
}

// WriteToRequest writes these params to a swagger request
func (o *CheckPermissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Access); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
