// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDecryptParams creates a new DecryptParams object
// with the default values initialized.
func NewDecryptParams() *DecryptParams {
	var ()
	return &DecryptParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDecryptParamsWithTimeout creates a new DecryptParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDecryptParamsWithTimeout(timeout time.Duration) *DecryptParams {
	var ()
	return &DecryptParams{

		timeout: timeout,
	}
}

// NewDecryptParamsWithContext creates a new DecryptParams object
// with the default values initialized, and the ability to set a context for a request
func NewDecryptParamsWithContext(ctx context.Context) *DecryptParams {
	var ()
	return &DecryptParams{

		Context: ctx,
	}
}

// NewDecryptParamsWithHTTPClient creates a new DecryptParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDecryptParamsWithHTTPClient(client *http.Client) *DecryptParams {
	var ()
	return &DecryptParams{
		HTTPClient: client,
	}
}

/*DecryptParams contains all the parameters to send to the API endpoint
for the decrypt operation typically these are written to a http.Request
*/
type DecryptParams struct {

	/*Parameters
	  parameters

	*/
	Parameters DecryptBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the decrypt params
func (o *DecryptParams) WithTimeout(timeout time.Duration) *DecryptParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the decrypt params
func (o *DecryptParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the decrypt params
func (o *DecryptParams) WithContext(ctx context.Context) *DecryptParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the decrypt params
func (o *DecryptParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the decrypt params
func (o *DecryptParams) WithHTTPClient(client *http.Client) *DecryptParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the decrypt params
func (o *DecryptParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParameters adds the parameters to the decrypt params
func (o *DecryptParams) WithParameters(parameters DecryptBody) *DecryptParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the decrypt params
func (o *DecryptParams) SetParameters(parameters DecryptBody) {
	o.Parameters = parameters
}

// WriteToRequest writes these params to a swagger request
func (o *DecryptParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
