// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSSHFSExportParams creates a new DeleteSSHFSExportParams object
// with the default values initialized.
func NewDeleteSSHFSExportParams() *DeleteSSHFSExportParams {
	var ()
	return &DeleteSSHFSExportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSSHFSExportParamsWithTimeout creates a new DeleteSSHFSExportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSSHFSExportParamsWithTimeout(timeout time.Duration) *DeleteSSHFSExportParams {
	var ()
	return &DeleteSSHFSExportParams{

		timeout: timeout,
	}
}

// NewDeleteSSHFSExportParamsWithContext creates a new DeleteSSHFSExportParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSSHFSExportParamsWithContext(ctx context.Context) *DeleteSSHFSExportParams {
	var ()
	return &DeleteSSHFSExportParams{

		Context: ctx,
	}
}

// NewDeleteSSHFSExportParamsWithHTTPClient creates a new DeleteSSHFSExportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSSHFSExportParamsWithHTTPClient(client *http.Client) *DeleteSSHFSExportParams {
	var ()
	return &DeleteSSHFSExportParams{
		HTTPClient: client,
	}
}

/*DeleteSSHFSExportParams contains all the parameters to send to the API endpoint
for the delete SSH f s export operation typically these are written to a http.Request
*/
type DeleteSSHFSExportParams struct {

	/*Parameters
	  parameters

	*/
	Parameters DeleteSSHFSExportBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) WithTimeout(timeout time.Duration) *DeleteSSHFSExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) WithContext(ctx context.Context) *DeleteSSHFSExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) WithHTTPClient(client *http.Client) *DeleteSSHFSExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParameters adds the parameters to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) WithParameters(parameters DeleteSSHFSExportBody) *DeleteSSHFSExportParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the delete SSH f s export params
func (o *DeleteSSHFSExportParams) SetParameters(parameters DeleteSSHFSExportBody) {
	o.Parameters = parameters
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSSHFSExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
