// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/lexis-project/lexis-backend-services-api.git/models"
)

// DeleteSSHFSExportReader is a Reader for the DeleteSSHFSExport structure.
type DeleteSSHFSExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSSHFSExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSSHFSExportNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSSHFSExportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteSSHFSExportUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteSSHFSExportForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteSSHFSExportNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewDeleteSSHFSExportBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteSSHFSExportServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSSHFSExportNoContent creates a DeleteSSHFSExportNoContent with default headers values
func NewDeleteSSHFSExportNoContent() *DeleteSSHFSExportNoContent {
	return &DeleteSSHFSExportNoContent{}
}

/*DeleteSSHFSExportNoContent handles this case with default header values.

Export removed
*/
type DeleteSSHFSExportNoContent struct {
}

func (o *DeleteSSHFSExportNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dataset/ssh/sshfsexport][%d] deleteSshFSExportNoContent ", 204)
}

func (o *DeleteSSHFSExportNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSSHFSExportBadRequest creates a DeleteSSHFSExportBadRequest with default headers values
func NewDeleteSSHFSExportBadRequest() *DeleteSSHFSExportBadRequest {
	return &DeleteSSHFSExportBadRequest{}
}

/*DeleteSSHFSExportBadRequest handles this case with default header values.

This means that there's something wrong in the input parameters and the server couldn't understand the request.
*/
type DeleteSSHFSExportBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSSHFSExportBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /dataset/ssh/sshfsexport][%d] deleteSshFSExportBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteSSHFSExportBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSSHFSExportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSSHFSExportUnauthorized creates a DeleteSSHFSExportUnauthorized with default headers values
func NewDeleteSSHFSExportUnauthorized() *DeleteSSHFSExportUnauthorized {
	return &DeleteSSHFSExportUnauthorized{}
}

/*DeleteSSHFSExportUnauthorized handles this case with default header values.

This means that the user is not authenticated with keycloak and data transfer can't be triggered unless the user first log in with a valid user
*/
type DeleteSSHFSExportUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSSHFSExportUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /dataset/ssh/sshfsexport][%d] deleteSshFSExportUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteSSHFSExportUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSSHFSExportUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSSHFSExportForbidden creates a DeleteSSHFSExportForbidden with default headers values
func NewDeleteSSHFSExportForbidden() *DeleteSSHFSExportForbidden {
	return &DeleteSSHFSExportForbidden{}
}

/*DeleteSSHFSExportForbidden handles this case with default header values.

This means that the resource the user is trying to transfer from or to is not readable or writable by the user. User doesn't have the correct rights to either read the source file or write on the target system location.
*/
type DeleteSSHFSExportForbidden struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSSHFSExportForbidden) Error() string {
	return fmt.Sprintf("[DELETE /dataset/ssh/sshfsexport][%d] deleteSshFSExportForbidden  %+v", 403, o.Payload)
}

func (o *DeleteSSHFSExportForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSSHFSExportForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSSHFSExportNotFound creates a DeleteSSHFSExportNotFound with default headers values
func NewDeleteSSHFSExportNotFound() *DeleteSSHFSExportNotFound {
	return &DeleteSSHFSExportNotFound{}
}

/*DeleteSSHFSExportNotFound handles this case with default header values.

The resource (username, path or both) does not exist
*/
type DeleteSSHFSExportNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSSHFSExportNotFound) Error() string {
	return fmt.Sprintf("[DELETE /dataset/ssh/sshfsexport][%d] deleteSshFSExportNotFound  %+v", 404, o.Payload)
}

func (o *DeleteSSHFSExportNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSSHFSExportNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSSHFSExportBadGateway creates a DeleteSSHFSExportBadGateway with default headers values
func NewDeleteSSHFSExportBadGateway() *DeleteSSHFSExportBadGateway {
	return &DeleteSSHFSExportBadGateway{}
}

/*DeleteSSHFSExportBadGateway handles this case with default header values.

bad gateway (backend service is down)
*/
type DeleteSSHFSExportBadGateway struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSSHFSExportBadGateway) Error() string {
	return fmt.Sprintf("[DELETE /dataset/ssh/sshfsexport][%d] deleteSshFSExportBadGateway  %+v", 502, o.Payload)
}

func (o *DeleteSSHFSExportBadGateway) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSSHFSExportBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSSHFSExportServiceUnavailable creates a DeleteSSHFSExportServiceUnavailable with default headers values
func NewDeleteSSHFSExportServiceUnavailable() *DeleteSSHFSExportServiceUnavailable {
	return &DeleteSSHFSExportServiceUnavailable{}
}

/*DeleteSSHFSExportServiceUnavailable handles this case with default header values.

unexpected error
*/
type DeleteSSHFSExportServiceUnavailable struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSSHFSExportServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /dataset/ssh/sshfsexport][%d] deleteSshFSExportServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteSSHFSExportServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSSHFSExportServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteSSHFSExportBody delete SSH f s export body
swagger:model DeleteSSHFSExportBody
*/
type DeleteSSHFSExportBody struct {

	// path
	// Required: true
	Path *string `json:"path"`

	// user
	// Required: true
	User *string `json:"user"`
}

// Validate validates this delete SSH f s export body
func (o *DeleteSSHFSExportBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePath(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteSSHFSExportBody) validatePath(formats strfmt.Registry) error {

	if err := validate.Required("parameters"+"."+"path", "body", o.Path); err != nil {
		return err
	}

	return nil
}

func (o *DeleteSSHFSExportBody) validateUser(formats strfmt.Registry) error {

	if err := validate.Required("parameters"+"."+"user", "body", o.User); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteSSHFSExportBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteSSHFSExportBody) UnmarshalBinary(b []byte) error {
	var res DeleteSSHFSExportBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
