// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFilesDeleteParams creates a new FilesDeleteParams object
// with the default values initialized.
func NewFilesDeleteParams() *FilesDeleteParams {
	var ()
	return &FilesDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFilesDeleteParamsWithTimeout creates a new FilesDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFilesDeleteParamsWithTimeout(timeout time.Duration) *FilesDeleteParams {
	var ()
	return &FilesDeleteParams{

		timeout: timeout,
	}
}

// NewFilesDeleteParamsWithContext creates a new FilesDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewFilesDeleteParamsWithContext(ctx context.Context) *FilesDeleteParams {
	var ()
	return &FilesDeleteParams{

		Context: ctx,
	}
}

// NewFilesDeleteParamsWithHTTPClient creates a new FilesDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFilesDeleteParamsWithHTTPClient(client *http.Client) *FilesDeleteParams {
	var ()
	return &FilesDeleteParams{
		HTTPClient: client,
	}
}

/*FilesDeleteParams contains all the parameters to send to the API endpoint
for the files delete operation typically these are written to a http.Request
*/
type FilesDeleteParams struct {

	/*TusResumable
	  Protocol version

	*/
	TusResumable string
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the files delete params
func (o *FilesDeleteParams) WithTimeout(timeout time.Duration) *FilesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the files delete params
func (o *FilesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the files delete params
func (o *FilesDeleteParams) WithContext(ctx context.Context) *FilesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the files delete params
func (o *FilesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the files delete params
func (o *FilesDeleteParams) WithHTTPClient(client *http.Client) *FilesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the files delete params
func (o *FilesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTusResumable adds the tusResumable to the files delete params
func (o *FilesDeleteParams) WithTusResumable(tusResumable string) *FilesDeleteParams {
	o.SetTusResumable(tusResumable)
	return o
}

// SetTusResumable adds the tusResumable to the files delete params
func (o *FilesDeleteParams) SetTusResumable(tusResumable string) {
	o.TusResumable = tusResumable
}

// WithID adds the id to the files delete params
func (o *FilesDeleteParams) WithID(id string) *FilesDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the files delete params
func (o *FilesDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FilesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Tus-Resumable
	if err := r.SetHeaderParam("Tus-Resumable", o.TusResumable); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
