// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPIDParams creates a new PIDParams object
// with the default values initialized.
func NewPIDParams() *PIDParams {
	var ()
	return &PIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPIDParamsWithTimeout creates a new PIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPIDParamsWithTimeout(timeout time.Duration) *PIDParams {
	var ()
	return &PIDParams{

		timeout: timeout,
	}
}

// NewPIDParamsWithContext creates a new PIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPIDParamsWithContext(ctx context.Context) *PIDParams {
	var ()
	return &PIDParams{

		Context: ctx,
	}
}

// NewPIDParamsWithHTTPClient creates a new PIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPIDParamsWithHTTPClient(client *http.Client) *PIDParams {
	var ()
	return &PIDParams{
		HTTPClient: client,
	}
}

/*PIDParams contains all the parameters to send to the API endpoint
for the p ID operation typically these are written to a http.Request
*/
type PIDParams struct {

	/*Parameters
	  parameters

	*/
	Parameters PIDBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p ID params
func (o *PIDParams) WithTimeout(timeout time.Duration) *PIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p ID params
func (o *PIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p ID params
func (o *PIDParams) WithContext(ctx context.Context) *PIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p ID params
func (o *PIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p ID params
func (o *PIDParams) WithHTTPClient(client *http.Client) *PIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p ID params
func (o *PIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParameters adds the parameters to the p ID params
func (o *PIDParams) WithParameters(parameters PIDBody) *PIDParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the p ID params
func (o *PIDParams) SetParameters(parameters PIDBody) {
	o.Parameters = parameters
}

// WriteToRequest writes these params to a swagger request
func (o *PIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
