// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSizeParams creates a new SizeParams object
// with the default values initialized.
func NewSizeParams() *SizeParams {
	var ()
	return &SizeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSizeParamsWithTimeout creates a new SizeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSizeParamsWithTimeout(timeout time.Duration) *SizeParams {
	var ()
	return &SizeParams{

		timeout: timeout,
	}
}

// NewSizeParamsWithContext creates a new SizeParams object
// with the default values initialized, and the ability to set a context for a request
func NewSizeParamsWithContext(ctx context.Context) *SizeParams {
	var ()
	return &SizeParams{

		Context: ctx,
	}
}

// NewSizeParamsWithHTTPClient creates a new SizeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSizeParamsWithHTTPClient(client *http.Client) *SizeParams {
	var ()
	return &SizeParams{
		HTTPClient: client,
	}
}

/*SizeParams contains all the parameters to send to the API endpoint
for the size operation typically these are written to a http.Request
*/
type SizeParams struct {

	/*Parameters
	  parameters

	*/
	Parameters SizeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the size params
func (o *SizeParams) WithTimeout(timeout time.Duration) *SizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the size params
func (o *SizeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the size params
func (o *SizeParams) WithContext(ctx context.Context) *SizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the size params
func (o *SizeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the size params
func (o *SizeParams) WithHTTPClient(client *http.Client) *SizeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the size params
func (o *SizeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParameters adds the parameters to the size params
func (o *SizeParams) WithParameters(parameters SizeBody) *SizeParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the size params
func (o *SizeParams) SetParameters(parameters SizeBody) {
	o.Parameters = parameters
}

// WriteToRequest writes these params to a swagger request
func (o *SizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
