// Code generated by go-swagger; DO NOT EDIT.

package usage_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/lexis-project/lexis-backend-services-api.git/models"
)

// GetUsageReader is a Reader for the GetUsage structure.
type GetUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetUsageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetUsageForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetUsageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetUsageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUsageOK creates a GetUsageOK with default headers values
func NewGetUsageOK() *GetUsageOK {
	return &GetUsageOK{}
}

/*GetUsageOK handles this case with default header values.

usage returned
*/
type GetUsageOK struct {
	Payload *models.Usage
}

func (o *GetUsageOK) Error() string {
	return fmt.Sprintf("[GET /accounting/{id}/usage][%d] getUsageOK  %+v", 200, o.Payload)
}

func (o *GetUsageOK) GetPayload() *models.Usage {
	return o.Payload
}

func (o *GetUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Usage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsageUnauthorized creates a GetUsageUnauthorized with default headers values
func NewGetUsageUnauthorized() *GetUsageUnauthorized {
	return &GetUsageUnauthorized{}
}

/*GetUsageUnauthorized handles this case with default header values.

Unauthorized
*/
type GetUsageUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *GetUsageUnauthorized) Error() string {
	return fmt.Sprintf("[GET /accounting/{id}/usage][%d] getUsageUnauthorized  %+v", 401, o.Payload)
}

func (o *GetUsageUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetUsageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsageForbidden creates a GetUsageForbidden with default headers values
func NewGetUsageForbidden() *GetUsageForbidden {
	return &GetUsageForbidden{}
}

/*GetUsageForbidden handles this case with default header values.

Forbidden
*/
type GetUsageForbidden struct {
	Payload *models.ErrorResponse
}

func (o *GetUsageForbidden) Error() string {
	return fmt.Sprintf("[GET /accounting/{id}/usage][%d] getUsageForbidden  %+v", 403, o.Payload)
}

func (o *GetUsageForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetUsageForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsageNotFound creates a GetUsageNotFound with default headers values
func NewGetUsageNotFound() *GetUsageNotFound {
	return &GetUsageNotFound{}
}

/*GetUsageNotFound handles this case with default header values.

project not found
*/
type GetUsageNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetUsageNotFound) Error() string {
	return fmt.Sprintf("[GET /accounting/{id}/usage][%d] getUsageNotFound  %+v", 404, o.Payload)
}

func (o *GetUsageNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetUsageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsageInternalServerError creates a GetUsageInternalServerError with default headers values
func NewGetUsageInternalServerError() *GetUsageInternalServerError {
	return &GetUsageInternalServerError{}
}

/*GetUsageInternalServerError handles this case with default header values.

unexpected error
*/
type GetUsageInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetUsageInternalServerError) Error() string {
	return fmt.Sprintf("[GET /accounting/{id}/usage][%d] getUsageInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUsageInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetUsageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
