// Code generated by go-swagger; DO NOT EDIT.

package workflow_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkflowTemplatesParams creates a new GetWorkflowTemplatesParams object
// with the default values initialized.
func NewGetWorkflowTemplatesParams() *GetWorkflowTemplatesParams {

	return &GetWorkflowTemplatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowTemplatesParamsWithTimeout creates a new GetWorkflowTemplatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowTemplatesParamsWithTimeout(timeout time.Duration) *GetWorkflowTemplatesParams {

	return &GetWorkflowTemplatesParams{

		timeout: timeout,
	}
}

// NewGetWorkflowTemplatesParamsWithContext creates a new GetWorkflowTemplatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkflowTemplatesParamsWithContext(ctx context.Context) *GetWorkflowTemplatesParams {

	return &GetWorkflowTemplatesParams{

		Context: ctx,
	}
}

// NewGetWorkflowTemplatesParamsWithHTTPClient creates a new GetWorkflowTemplatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkflowTemplatesParamsWithHTTPClient(client *http.Client) *GetWorkflowTemplatesParams {

	return &GetWorkflowTemplatesParams{
		HTTPClient: client,
	}
}

/*GetWorkflowTemplatesParams contains all the parameters to send to the API endpoint
for the get workflow templates operation typically these are written to a http.Request
*/
type GetWorkflowTemplatesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get workflow templates params
func (o *GetWorkflowTemplatesParams) WithTimeout(timeout time.Duration) *GetWorkflowTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow templates params
func (o *GetWorkflowTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow templates params
func (o *GetWorkflowTemplatesParams) WithContext(ctx context.Context) *GetWorkflowTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow templates params
func (o *GetWorkflowTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow templates params
func (o *GetWorkflowTemplatesParams) WithHTTPClient(client *http.Client) *GetWorkflowTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow templates params
func (o *GetWorkflowTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
