// Code generated by go-swagger; DO NOT EDIT.

package staging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCloudNFSExportAddParams creates a new CloudNFSExportAddParams object
// with the default values initialized.
func NewCloudNFSExportAddParams() *CloudNFSExportAddParams {
	var ()
	return &CloudNFSExportAddParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCloudNFSExportAddParamsWithTimeout creates a new CloudNFSExportAddParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCloudNFSExportAddParamsWithTimeout(timeout time.Duration) *CloudNFSExportAddParams {
	var ()
	return &CloudNFSExportAddParams{

		timeout: timeout,
	}
}

// NewCloudNFSExportAddParamsWithContext creates a new CloudNFSExportAddParams object
// with the default values initialized, and the ability to set a context for a request
func NewCloudNFSExportAddParamsWithContext(ctx context.Context) *CloudNFSExportAddParams {
	var ()
	return &CloudNFSExportAddParams{

		Context: ctx,
	}
}

// NewCloudNFSExportAddParamsWithHTTPClient creates a new CloudNFSExportAddParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCloudNFSExportAddParamsWithHTTPClient(client *http.Client) *CloudNFSExportAddParams {
	var ()
	return &CloudNFSExportAddParams{
		HTTPClient: client,
	}
}

/*CloudNFSExportAddParams contains all the parameters to send to the API endpoint
for the cloud n f s export add operation typically these are written to a http.Request
*/
type CloudNFSExportAddParams struct {

	/*Param
	  IP of the cloud machine

	*/
	Param string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cloud n f s export add params
func (o *CloudNFSExportAddParams) WithTimeout(timeout time.Duration) *CloudNFSExportAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cloud n f s export add params
func (o *CloudNFSExportAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cloud n f s export add params
func (o *CloudNFSExportAddParams) WithContext(ctx context.Context) *CloudNFSExportAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cloud n f s export add params
func (o *CloudNFSExportAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cloud n f s export add params
func (o *CloudNFSExportAddParams) WithHTTPClient(client *http.Client) *CloudNFSExportAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cloud n f s export add params
func (o *CloudNFSExportAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParam adds the param to the cloud n f s export add params
func (o *CloudNFSExportAddParams) WithParam(param string) *CloudNFSExportAddParams {
	o.SetParam(param)
	return o
}

// SetParam adds the param to the cloud n f s export add params
func (o *CloudNFSExportAddParams) SetParam(param string) {
	o.Param = param
}

// WriteToRequest writes these params to a swagger request
func (o *CloudNFSExportAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param param
	if err := r.SetPathParam("param", o.Param); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
