// Code generated by go-swagger; DO NOT EDIT.

package staging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/lexis-project/lexis-backend-services-api.git/models"
)

// CloudNFSExportRemoveReader is a Reader for the CloudNFSExportRemove structure.
type CloudNFSExportRemoveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CloudNFSExportRemoveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCloudNFSExportRemoveCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCloudNFSExportRemoveBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCloudNFSExportRemoveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 414:
		result := NewCloudNFSExportRemoveRequestURITooLong()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCloudNFSExportRemoveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCloudNFSExportRemoveCreated creates a CloudNFSExportRemoveCreated with default headers values
func NewCloudNFSExportRemoveCreated() *CloudNFSExportRemoveCreated {
	return &CloudNFSExportRemoveCreated{}
}

/*CloudNFSExportRemoveCreated handles this case with default header values.

The response code means that the request for removal has been initiated. Status of the removal process can be checked by querying the status.
*/
type CloudNFSExportRemoveCreated struct {
	Payload *models.SteeringRequestID
}

func (o *CloudNFSExportRemoveCreated) Error() string {
	return fmt.Sprintf("[POST /dataset/cloud/remove/{param}][%d] cloudNFSExportRemoveCreated  %+v", 201, o.Payload)
}

func (o *CloudNFSExportRemoveCreated) GetPayload() *models.SteeringRequestID {
	return o.Payload
}

func (o *CloudNFSExportRemoveCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SteeringRequestID)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudNFSExportRemoveBadRequest creates a CloudNFSExportRemoveBadRequest with default headers values
func NewCloudNFSExportRemoveBadRequest() *CloudNFSExportRemoveBadRequest {
	return &CloudNFSExportRemoveBadRequest{}
}

/*CloudNFSExportRemoveBadRequest handles this case with default header values.

This means that the request ID given by the user is incorrect.
*/
type CloudNFSExportRemoveBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *CloudNFSExportRemoveBadRequest) Error() string {
	return fmt.Sprintf("[POST /dataset/cloud/remove/{param}][%d] cloudNFSExportRemoveBadRequest  %+v", 400, o.Payload)
}

func (o *CloudNFSExportRemoveBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CloudNFSExportRemoveBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudNFSExportRemoveUnauthorized creates a CloudNFSExportRemoveUnauthorized with default headers values
func NewCloudNFSExportRemoveUnauthorized() *CloudNFSExportRemoveUnauthorized {
	return &CloudNFSExportRemoveUnauthorized{}
}

/*CloudNFSExportRemoveUnauthorized handles this case with default header values.

This means that the user is not authenticated with keycloak and data transfer can't be triggered unless the user first log in with a valid user
*/
type CloudNFSExportRemoveUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *CloudNFSExportRemoveUnauthorized) Error() string {
	return fmt.Sprintf("[POST /dataset/cloud/remove/{param}][%d] cloudNFSExportRemoveUnauthorized  %+v", 401, o.Payload)
}

func (o *CloudNFSExportRemoveUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CloudNFSExportRemoveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudNFSExportRemoveRequestURITooLong creates a CloudNFSExportRemoveRequestURITooLong with default headers values
func NewCloudNFSExportRemoveRequestURITooLong() *CloudNFSExportRemoveRequestURITooLong {
	return &CloudNFSExportRemoveRequestURITooLong{}
}

/*CloudNFSExportRemoveRequestURITooLong handles this case with default header values.

This means that the the request ID is longer than the server is willing to interpret.
*/
type CloudNFSExportRemoveRequestURITooLong struct {
	Payload *models.ErrorResponse
}

func (o *CloudNFSExportRemoveRequestURITooLong) Error() string {
	return fmt.Sprintf("[POST /dataset/cloud/remove/{param}][%d] cloudNFSExportRemoveRequestUriTooLong  %+v", 414, o.Payload)
}

func (o *CloudNFSExportRemoveRequestURITooLong) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CloudNFSExportRemoveRequestURITooLong) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudNFSExportRemoveInternalServerError creates a CloudNFSExportRemoveInternalServerError with default headers values
func NewCloudNFSExportRemoveInternalServerError() *CloudNFSExportRemoveInternalServerError {
	return &CloudNFSExportRemoveInternalServerError{}
}

/*CloudNFSExportRemoveInternalServerError handles this case with default header values.

This means that something has gone wrong on the data transfer steering server. The user is advised to wait and send the request again.
*/
type CloudNFSExportRemoveInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *CloudNFSExportRemoveInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dataset/cloud/remove/{param}][%d] cloudNFSExportRemoveInternalServerError  %+v", 500, o.Payload)
}

func (o *CloudNFSExportRemoveInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CloudNFSExportRemoveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
