// Code generated by go-swagger; DO NOT EDIT.

package staging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDuplicateParams creates a new DuplicateParams object
// with the default values initialized.
func NewDuplicateParams() *DuplicateParams {
	var ()
	return &DuplicateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDuplicateParamsWithTimeout creates a new DuplicateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDuplicateParamsWithTimeout(timeout time.Duration) *DuplicateParams {
	var ()
	return &DuplicateParams{

		timeout: timeout,
	}
}

// NewDuplicateParamsWithContext creates a new DuplicateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDuplicateParamsWithContext(ctx context.Context) *DuplicateParams {
	var ()
	return &DuplicateParams{

		Context: ctx,
	}
}

// NewDuplicateParamsWithHTTPClient creates a new DuplicateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDuplicateParamsWithHTTPClient(client *http.Client) *DuplicateParams {
	var ()
	return &DuplicateParams{
		HTTPClient: client,
	}
}

/*DuplicateParams contains all the parameters to send to the API endpoint
for the duplicate operation typically these are written to a http.Request
*/
type DuplicateParams struct {

	/*Parameters
	  parameters

	*/
	Parameters DuplicateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the duplicate params
func (o *DuplicateParams) WithTimeout(timeout time.Duration) *DuplicateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the duplicate params
func (o *DuplicateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the duplicate params
func (o *DuplicateParams) WithContext(ctx context.Context) *DuplicateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the duplicate params
func (o *DuplicateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the duplicate params
func (o *DuplicateParams) WithHTTPClient(client *http.Client) *DuplicateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the duplicate params
func (o *DuplicateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParameters adds the parameters to the duplicate params
func (o *DuplicateParams) WithParameters(parameters DuplicateBody) *DuplicateParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the duplicate params
func (o *DuplicateParams) SetParameters(parameters DuplicateBody) {
	o.Parameters = parameters
}

// WriteToRequest writes these params to a swagger request
func (o *DuplicateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
