// Code generated by go-swagger; DO NOT EDIT.

package staging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CheckDeletionStatusHandlerFunc turns a function with the right signature into a check deletion status handler
type CheckDeletionStatusHandlerFunc func(CheckDeletionStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckDeletionStatusHandlerFunc) Handle(params CheckDeletionStatusParams) middleware.Responder {
	return fn(params)
}

// CheckDeletionStatusHandler interface for that can handle valid check deletion status params
type CheckDeletionStatusHandler interface {
	Handle(CheckDeletionStatusParams) middleware.Responder
}

// NewCheckDeletionStatus creates a new http.Handler for the check deletion status operation
func NewCheckDeletionStatus(ctx *middleware.Context, handler CheckDeletionStatusHandler) *CheckDeletionStatus {
	return &CheckDeletionStatus{Context: ctx, Handler: handler}
}

/*CheckDeletionStatus swagger:route GET /dataset/staging/delete/{request_id} staging dataSetManagement checkDeletionStatus

Check the status of a delete request

On successful query (200), the status provides information about the result:
 - "Task still in the queue, or task does not exist": The request was not yet enqueued. Wait for a few seconds and retry
 - "Task Failed, reason: <specific reason>": The dataset could not be deleted
 - "Data deleted": The dataset was deleted successfully
 - "In progress": The deletion is in progress, wait a few seconds and retry.


*/
type CheckDeletionStatus struct {
	Context *middleware.Context
	Handler CheckDeletionStatusHandler
}

func (o *CheckDeletionStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCheckDeletionStatusParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CheckDeletionStatusOKBody check deletion status o k body
//
// swagger:model CheckDeletionStatusOKBody
type CheckDeletionStatusOKBody struct {

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this check deletion status o k body
func (o *CheckDeletionStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CheckDeletionStatusOKBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("checkDeletionStatusOK"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CheckDeletionStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CheckDeletionStatusOKBody) UnmarshalBinary(b []byte) error {
	var res CheckDeletionStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
