// Code generated by go-swagger; DO NOT EDIT.

package staging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CloudNFSExportRemoveHandlerFunc turns a function with the right signature into a cloud n f s export remove handler
type CloudNFSExportRemoveHandlerFunc func(CloudNFSExportRemoveParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CloudNFSExportRemoveHandlerFunc) Handle(params CloudNFSExportRemoveParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CloudNFSExportRemoveHandler interface for that can handle valid cloud n f s export remove params
type CloudNFSExportRemoveHandler interface {
	Handle(CloudNFSExportRemoveParams, interface{}) middleware.Responder
}

// NewCloudNFSExportRemove creates a new http.Handler for the cloud n f s export remove operation
func NewCloudNFSExportRemove(ctx *middleware.Context, handler CloudNFSExportRemoveHandler) *CloudNFSExportRemove {
	return &CloudNFSExportRemove{Context: ctx, Handler: handler}
}

/*CloudNFSExportRemove swagger:route POST /dataset/cloud/remove/{param} staging cloudNFSExportRemove

Request that an nfs export be removed for an LRZ cloud instance

Request that an nfs export be removed for an LRZ cloud instance

*/
type CloudNFSExportRemove struct {
	Context *middleware.Context
	Handler CloudNFSExportRemoveHandler
}

func (o *CloudNFSExportRemove) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCloudNFSExportRemoveParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
