// Code generated by go-swagger; DO NOT EDIT.

package cluster_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCommandTemplateHandlerFunc turns a function with the right signature into a get command template handler
type GetCommandTemplateHandlerFunc func(GetCommandTemplateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCommandTemplateHandlerFunc) Handle(params GetCommandTemplateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCommandTemplateHandler interface for that can handle valid get command template params
type GetCommandTemplateHandler interface {
	Handle(GetCommandTemplateParams, interface{}) middleware.Responder
}

// NewGetCommandTemplate creates a new http.Handler for the get command template operation
func NewGetCommandTemplate(ctx *middleware.Context, handler GetCommandTemplateHandler) *GetCommandTemplate {
	return &GetCommandTemplate{Context: ctx, Handler: handler}
}

/*GetCommandTemplate swagger:route POST /heappe/ClusterInformation/GetCommandTemplateParametersName ClusterInformation getCommandTemplate

Get command template parameters name

Get command template parameters name

*/
type GetCommandTemplate struct {
	Context *middleware.Context
	Handler GetCommandTemplateHandler
}

func (o *GetCommandTemplate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCommandTemplateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
