// Code generated by go-swagger; DO NOT EDIT.

package user_org_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/lexis-project/lexis-backend-services-api.git/models"
)

// DeleteHPCResourceOKCode is the HTTP code returned for type DeleteHPCResourceOK
const DeleteHPCResourceOKCode int = 200

/*DeleteHPCResourceOK deleted HPCResource

swagger:response deleteHPCResourceOK
*/
type DeleteHPCResourceOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeletedResponse `json:"body,omitempty"`
}

// NewDeleteHPCResourceOK creates DeleteHPCResourceOK with default headers values
func NewDeleteHPCResourceOK() *DeleteHPCResourceOK {

	return &DeleteHPCResourceOK{}
}

// WithPayload adds the payload to the delete h p c resource o k response
func (o *DeleteHPCResourceOK) WithPayload(payload *models.DeletedResponse) *DeleteHPCResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete h p c resource o k response
func (o *DeleteHPCResourceOK) SetPayload(payload *models.DeletedResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHPCResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHPCResourceUnauthorizedCode is the HTTP code returned for type DeleteHPCResourceUnauthorized
const DeleteHPCResourceUnauthorizedCode int = 401

/*DeleteHPCResourceUnauthorized Unauthorized

swagger:response deleteHPCResourceUnauthorized
*/
type DeleteHPCResourceUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteHPCResourceUnauthorized creates DeleteHPCResourceUnauthorized with default headers values
func NewDeleteHPCResourceUnauthorized() *DeleteHPCResourceUnauthorized {

	return &DeleteHPCResourceUnauthorized{}
}

// WithPayload adds the payload to the delete h p c resource unauthorized response
func (o *DeleteHPCResourceUnauthorized) WithPayload(payload *models.ErrorResponse) *DeleteHPCResourceUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete h p c resource unauthorized response
func (o *DeleteHPCResourceUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHPCResourceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHPCResourceForbiddenCode is the HTTP code returned for type DeleteHPCResourceForbidden
const DeleteHPCResourceForbiddenCode int = 403

/*DeleteHPCResourceForbidden Forbidden

swagger:response deleteHPCResourceForbidden
*/
type DeleteHPCResourceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteHPCResourceForbidden creates DeleteHPCResourceForbidden with default headers values
func NewDeleteHPCResourceForbidden() *DeleteHPCResourceForbidden {

	return &DeleteHPCResourceForbidden{}
}

// WithPayload adds the payload to the delete h p c resource forbidden response
func (o *DeleteHPCResourceForbidden) WithPayload(payload *models.ErrorResponse) *DeleteHPCResourceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete h p c resource forbidden response
func (o *DeleteHPCResourceForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHPCResourceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHPCResourceNotFoundCode is the HTTP code returned for type DeleteHPCResourceNotFound
const DeleteHPCResourceNotFoundCode int = 404

/*DeleteHPCResourceNotFound HPCResource with not found

swagger:response deleteHPCResourceNotFound
*/
type DeleteHPCResourceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteHPCResourceNotFound creates DeleteHPCResourceNotFound with default headers values
func NewDeleteHPCResourceNotFound() *DeleteHPCResourceNotFound {

	return &DeleteHPCResourceNotFound{}
}

// WithPayload adds the payload to the delete h p c resource not found response
func (o *DeleteHPCResourceNotFound) WithPayload(payload *models.ErrorResponse) *DeleteHPCResourceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete h p c resource not found response
func (o *DeleteHPCResourceNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHPCResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHPCResourceInternalServerErrorCode is the HTTP code returned for type DeleteHPCResourceInternalServerError
const DeleteHPCResourceInternalServerErrorCode int = 500

/*DeleteHPCResourceInternalServerError unexpected error

swagger:response deleteHPCResourceInternalServerError
*/
type DeleteHPCResourceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteHPCResourceInternalServerError creates DeleteHPCResourceInternalServerError with default headers values
func NewDeleteHPCResourceInternalServerError() *DeleteHPCResourceInternalServerError {

	return &DeleteHPCResourceInternalServerError{}
}

// WithPayload adds the payload to the delete h p c resource internal server error response
func (o *DeleteHPCResourceInternalServerError) WithPayload(payload *models.ErrorResponse) *DeleteHPCResourceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete h p c resource internal server error response
func (o *DeleteHPCResourceInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHPCResourceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
