// Code generated by go-swagger; DO NOT EDIT.

package user_org_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/lexis-project/lexis-backend-services-api.git/models"
)

// ListHPCResourcesOKCode is the HTTP code returned for type ListHPCResourcesOK
const ListHPCResourcesOKCode int = 200

/*ListHPCResourcesOK list of HPCResources

swagger:response listHPCResourcesOK
*/
type ListHPCResourcesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.HPCResource `json:"body,omitempty"`
}

// NewListHPCResourcesOK creates ListHPCResourcesOK with default headers values
func NewListHPCResourcesOK() *ListHPCResourcesOK {

	return &ListHPCResourcesOK{}
}

// WithPayload adds the payload to the list h p c resources o k response
func (o *ListHPCResourcesOK) WithPayload(payload []*models.HPCResource) *ListHPCResourcesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list h p c resources o k response
func (o *ListHPCResourcesOK) SetPayload(payload []*models.HPCResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListHPCResourcesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.HPCResource, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListHPCResourcesUnauthorizedCode is the HTTP code returned for type ListHPCResourcesUnauthorized
const ListHPCResourcesUnauthorizedCode int = 401

/*ListHPCResourcesUnauthorized Unauthorized

swagger:response listHPCResourcesUnauthorized
*/
type ListHPCResourcesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewListHPCResourcesUnauthorized creates ListHPCResourcesUnauthorized with default headers values
func NewListHPCResourcesUnauthorized() *ListHPCResourcesUnauthorized {

	return &ListHPCResourcesUnauthorized{}
}

// WithPayload adds the payload to the list h p c resources unauthorized response
func (o *ListHPCResourcesUnauthorized) WithPayload(payload *models.ErrorResponse) *ListHPCResourcesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list h p c resources unauthorized response
func (o *ListHPCResourcesUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListHPCResourcesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListHPCResourcesForbiddenCode is the HTTP code returned for type ListHPCResourcesForbidden
const ListHPCResourcesForbiddenCode int = 403

/*ListHPCResourcesForbidden Forbidden

swagger:response listHPCResourcesForbidden
*/
type ListHPCResourcesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewListHPCResourcesForbidden creates ListHPCResourcesForbidden with default headers values
func NewListHPCResourcesForbidden() *ListHPCResourcesForbidden {

	return &ListHPCResourcesForbidden{}
}

// WithPayload adds the payload to the list h p c resources forbidden response
func (o *ListHPCResourcesForbidden) WithPayload(payload *models.ErrorResponse) *ListHPCResourcesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list h p c resources forbidden response
func (o *ListHPCResourcesForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListHPCResourcesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListHPCResourcesInternalServerErrorCode is the HTTP code returned for type ListHPCResourcesInternalServerError
const ListHPCResourcesInternalServerErrorCode int = 500

/*ListHPCResourcesInternalServerError unexpected error

swagger:response listHPCResourcesInternalServerError
*/
type ListHPCResourcesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewListHPCResourcesInternalServerError creates ListHPCResourcesInternalServerError with default headers values
func NewListHPCResourcesInternalServerError() *ListHPCResourcesInternalServerError {

	return &ListHPCResourcesInternalServerError{}
}

// WithPayload adds the payload to the list h p c resources internal server error response
func (o *ListHPCResourcesInternalServerError) WithPayload(payload *models.ErrorResponse) *ListHPCResourcesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list h p c resources internal server error response
func (o *ListHPCResourcesInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListHPCResourcesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
