// Code generated by go-swagger; DO NOT EDIT.

package approval_system_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// HPCApprovedResourceRequestHandlerFunc turns a function with the right signature into a h p c approved resource request handler
type HPCApprovedResourceRequestHandlerFunc func(HPCApprovedResourceRequestParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn HPCApprovedResourceRequestHandlerFunc) Handle(params HPCApprovedResourceRequestParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// HPCApprovedResourceRequestHandler interface for that can handle valid h p c approved resource request params
type HPCApprovedResourceRequestHandler interface {
	Handle(HPCApprovedResourceRequestParams, interface{}) middleware.Responder
}

// NewHPCApprovedResourceRequest creates a new http.Handler for the h p c approved resource request operation
func NewHPCApprovedResourceRequest(ctx *middleware.Context, handler HPCApprovedResourceRequestHandler) *HPCApprovedResourceRequest {
	return &HPCApprovedResourceRequest{Context: ctx, Handler: handler}
}

/*HPCApprovedResourceRequest swagger:route GET /approval_system/approvedResourceRequest/{HPCResourceID} approvalSystemManagement hPCApprovedResourceRequest

Get specific approved resources request from approval system

Gets an HPC approved resource request by ID of associated HPC resource.

*/
type HPCApprovedResourceRequest struct {
	Context *middleware.Context
	Handler HPCApprovedResourceRequestHandler
}

func (o *HPCApprovedResourceRequest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewHPCApprovedResourceRequestParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
