// Code generated by go-swagger; DO NOT EDIT.

package approval_system_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewListProjectHPCApprovedResourceRequestParams creates a new ListProjectHPCApprovedResourceRequestParams object
// no default values defined in spec.
func NewListProjectHPCApprovedResourceRequestParams() ListProjectHPCApprovedResourceRequestParams {

	return ListProjectHPCApprovedResourceRequestParams{}
}

// ListProjectHPCApprovedResourceRequestParams contains all the bound params for the list project h p c approved resource request operation
// typically these are obtained from a http.Request
//
// swagger:parameters listProjectHPCApprovedResourceRequest
type ListProjectHPCApprovedResourceRequestParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*LEXIS project ID
	  Required: true
	  In: path
	*/
	AssociatedLEXISProject string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListProjectHPCApprovedResourceRequestParams() beforehand.
func (o *ListProjectHPCApprovedResourceRequestParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAssociatedLEXISProject, rhkAssociatedLEXISProject, _ := route.Params.GetOK("AssociatedLEXISProject")
	if err := o.bindAssociatedLEXISProject(rAssociatedLEXISProject, rhkAssociatedLEXISProject, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAssociatedLEXISProject binds and validates parameter AssociatedLEXISProject from path.
func (o *ListProjectHPCApprovedResourceRequestParams) bindAssociatedLEXISProject(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.AssociatedLEXISProject = raw

	return nil
}
