// Code generated by go-swagger; DO NOT EDIT.

package approval_system_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProjectHPCApprovedResourceRequestParams creates a new ListProjectHPCApprovedResourceRequestParams object
// with the default values initialized.
func NewListProjectHPCApprovedResourceRequestParams() *ListProjectHPCApprovedResourceRequestParams {
	var ()
	return &ListProjectHPCApprovedResourceRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListProjectHPCApprovedResourceRequestParamsWithTimeout creates a new ListProjectHPCApprovedResourceRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListProjectHPCApprovedResourceRequestParamsWithTimeout(timeout time.Duration) *ListProjectHPCApprovedResourceRequestParams {
	var ()
	return &ListProjectHPCApprovedResourceRequestParams{

		timeout: timeout,
	}
}

// NewListProjectHPCApprovedResourceRequestParamsWithContext creates a new ListProjectHPCApprovedResourceRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewListProjectHPCApprovedResourceRequestParamsWithContext(ctx context.Context) *ListProjectHPCApprovedResourceRequestParams {
	var ()
	return &ListProjectHPCApprovedResourceRequestParams{

		Context: ctx,
	}
}

// NewListProjectHPCApprovedResourceRequestParamsWithHTTPClient creates a new ListProjectHPCApprovedResourceRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListProjectHPCApprovedResourceRequestParamsWithHTTPClient(client *http.Client) *ListProjectHPCApprovedResourceRequestParams {
	var ()
	return &ListProjectHPCApprovedResourceRequestParams{
		HTTPClient: client,
	}
}

/*ListProjectHPCApprovedResourceRequestParams contains all the parameters to send to the API endpoint
for the list project h p c approved resource request operation typically these are written to a http.Request
*/
type ListProjectHPCApprovedResourceRequestParams struct {

	/*AssociatedLEXISProject
	  LEXIS project ID

	*/
	AssociatedLEXISProject string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) WithTimeout(timeout time.Duration) *ListProjectHPCApprovedResourceRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) WithContext(ctx context.Context) *ListProjectHPCApprovedResourceRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) WithHTTPClient(client *http.Client) *ListProjectHPCApprovedResourceRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssociatedLEXISProject adds the associatedLEXISProject to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) WithAssociatedLEXISProject(associatedLEXISProject string) *ListProjectHPCApprovedResourceRequestParams {
	o.SetAssociatedLEXISProject(associatedLEXISProject)
	return o
}

// SetAssociatedLEXISProject adds the associatedLEXISProject to the list project h p c approved resource request params
func (o *ListProjectHPCApprovedResourceRequestParams) SetAssociatedLEXISProject(associatedLEXISProject string) {
	o.AssociatedLEXISProject = associatedLEXISProject
}

// WriteToRequest writes these params to a swagger request
func (o *ListProjectHPCApprovedResourceRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param AssociatedLEXISProject
	if err := r.SetPathParam("AssociatedLEXISProject", o.AssociatedLEXISProject); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
