// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CertificateHandlerFunc turns a function with the right signature into a certificate handler
type CertificateHandlerFunc func(CertificateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CertificateHandlerFunc) Handle(params CertificateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CertificateHandler interface for that can handle valid certificate params
type CertificateHandler interface {
	Handle(CertificateParams, interface{}) middleware.Responder
}

// NewCertificate creates a new http.Handler for the certificate operation
func NewCertificate(ctx *middleware.Context, handler CertificateHandler) *Certificate {
	return &Certificate{Context: ctx, Handler: handler}
}

/*Certificate swagger:route GET /dataset/cert dataSetManagement certificate

download public key for WP3 APIs

download public key for WP3 APIs

*/
type Certificate struct {
	Context *middleware.Context
	Handler CertificateHandler
}

func (o *Certificate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCertificateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
