// Code generated by go-swagger; DO NOT EDIT.

package data_set_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CheckDecryptionDecompressionStatusHandlerFunc turns a function with the right signature into a check decryption decompression status handler
type CheckDecryptionDecompressionStatusHandlerFunc func(CheckDecryptionDecompressionStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckDecryptionDecompressionStatusHandlerFunc) Handle(params CheckDecryptionDecompressionStatusParams) middleware.Responder {
	return fn(params)
}

// CheckDecryptionDecompressionStatusHandler interface for that can handle valid check decryption decompression status params
type CheckDecryptionDecompressionStatusHandler interface {
	Handle(CheckDecryptionDecompressionStatusParams) middleware.Responder
}

// NewCheckDecryptionDecompressionStatus creates a new http.Handler for the check decryption decompression status operation
func NewCheckDecryptionDecompressionStatus(ctx *middleware.Context, handler CheckDecryptionDecompressionStatusHandler) *CheckDecryptionDecompressionStatus {
	return &CheckDecryptionDecompressionStatus{Context: ctx, Handler: handler}
}

/*CheckDecryptionDecompressionStatus swagger:route GET /dataset/encryption/decrypt_decompress/{request_id} dataSetManagement checkDecryptionDecompressionStatus

Check the status of decryption with decompression

Check the status of decryption with decompression

*/
type CheckDecryptionDecompressionStatus struct {
	Context *middleware.Context
	Handler CheckDecryptionDecompressionStatusHandler
}

func (o *CheckDecryptionDecompressionStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCheckDecryptionDecompressionStatusParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CheckDecryptionDecompressionStatusOKBody check decryption decompression status o k body
//
// swagger:model CheckDecryptionDecompressionStatusOKBody
type CheckDecryptionDecompressionStatusOKBody struct {

	// status
	// Required: true
	Status *string `json:"status"`

	// Single path for encryption endpoints
	TargetPath string `json:"target_path,omitempty"`
}

// Validate validates this check decryption decompression status o k body
func (o *CheckDecryptionDecompressionStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CheckDecryptionDecompressionStatusOKBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("checkDecryptionDecompressionStatusOK"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CheckDecryptionDecompressionStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CheckDecryptionDecompressionStatusOKBody) UnmarshalBinary(b []byte) error {
	var res CheckDecryptionDecompressionStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
