// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Workflow workflow
//
// swagger:model Workflow
type Workflow struct {

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// creation time
	CreationTime string `json:"creationTime,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// project ID
	ProjectID string `json:"projectID,omitempty"`

	// project name
	ProjectName string `json:"projectName,omitempty"`

	// workflow ID
	WorkflowID string `json:"workflowID,omitempty"`

	// workflow name
	WorkflowName string `json:"workflowName,omitempty"`

	// workflow template ID
	WorkflowTemplateID string `json:"workflowTemplateID,omitempty"`
}

// Validate validates this workflow
func (m *Workflow) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Workflow) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Workflow) UnmarshalBinary(b []byte) error {
	var res Workflow
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
